config/routes.rb
Rails.application.routes.draw do

  get '/'             => 'comedians#index'
  get '/search' => 'comedians#search'
  get '/comedian/new' => 'comedians#new'
  post '/comedian/new' => 'comedians#create'
  get '/comedian/:id' => 'comedians#show'

  get '/signup'  => 'users#new'
  post '/signup' => 'users#create'
  
  get '/user/suggestions' => 'users#suggestions'
  get '/user/likes'       => 'users#likes' 
  post '/user/likes'      => 'likes#create'
  delete '/user/likes'    => 'likes#delete'

  get '/login'     => 'sessions#show'
  post '/login'    => 'sessions#login'
  delete '/logout' => 'sessions#logout'  

end

app/models/comedian.rb
class Comedian < ActiveRecord::Base
  has_many :tags
  has_many :likes
  has_many :fans, through: :likes, source: 'user'


  def similar_comedians
    Comedian.find_by_sql([SIMILAR_QUERY, {comedian: self.id}]) - [self]
  end

  # def similar_comedians
  #   list = []
  #   fans.each do |fan|
  #     fan.liked_comedians.each do |comedian|
  #       list << comedian unless comedian == self
  #     end
  #   end
  #   counts = list.each_with_object(Hash.new(0)) { |list,counts| counts[list] += 1 }
  #   sorted = counts.sort_by { |_,count| -count }.to_h
  #   sorted.map { |comedian,_| comedian }
  # end

  private

  SIMILAR_QUERY=<<-SQL
    SELECT count(c.id) AS score, c.* FROM likes l 
      JOIN users u ON u.id = l.user_id
      JOIN likes l2 ON u.id = l2.user_id
      JOIN comedians c ON l2.comedian_id = c.id
    WHERE l.comedian_id = :comedian
    GROUP BY c.id
    ORDER BY score DESC;
  SQL


end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :comedian
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :comedian
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :likes
  has_many :liked_comedians, through: :likes, source: 'comedian'
  validates_presence_of :password
  validates_confirmation_of :password

  def self.create_anonymous!
    User.create(password: SecureRandom.uuid)
  end

  def anonymous?
    email.nil? && persisted?
  end

  def suggested_comedians
    list = []
    liked_comedians.each do |comedian|
      comedian.similar_comedians.each do |comedian|
        list << comedian unless liked_comedians.include? comedian
      end
    end
    counts = list.each_with_object(Hash.new(0)) { |list,counts| counts[list] += 1 }
    sorted = counts.sort_by { |_,count| -count }.to_h
    sorted.map { |comedian,_| comedian }
  end

  def has_likes?
    !liked_comedians.empty?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

 def current_user      
    user = User.find_by(id: session[:user_id])

    unless user
      user = User.create_anonymous!
      session[:user_id] = user.id
    end
    user
  end

  def logged_in?
    !current_user.anonymous?
  end

end

app/controllers/comedians_controller.rb
class ComediansController < ApplicationController
  
  def index
    @comedians = Comedian.all.shuffle
  end

  def show
    @comedian = Comedian.find(params[:id])
  end
  
  def search
    @comedians = Comedian.where("name ilike ?","%#{params[:search]}%")
    render :index
  end 

  def new
  end

  def create
    render :new
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    Like.create(user_id: current_user.id, comedian_id: params[:comedian_id])
    head :created
  end

  def delete
    like = Like.find_by(user_id: current_user.id, comedian_id: params[:comedian_id])
    
    if like.nil?
      head :not_found 
      return
    end

    like.destroy
    head :no_content
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def show
  end

  def login    
    current_user.destroy if current_user.anonymous?
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to'/'
    else
      redirect_to '/login', alert: "Incorrect login details" 
    end
  end

  def logout
    session.clear
    redirect_to '/'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end
  
  def create
    if current_user.anonymous?
      saved = current_user.update(name: params[:user][:name], email: params[:user][:email], 
                          password: params[:user][:password], 
                          password_confirmation: params[:user][:password_confirmation])
      unless saved
        redirect_to '/signup', alert: "Passwords don't match"
        return
      end
    end
    redirect_to '/'
  end

  def likes
    @comedians = current_user.liked_comedians
  end

  def suggestions
    @comedians = current_user.suggested_comedians
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comedians/index.html.erb
<div class="container">

  <% if @comedians.empty? %>
    <h3 class="flow-text heading">No comedians match that criteria!</h3>
    <a href="/" class="btn waves-effect waves-light">BACK</a>
  <% end %>

  <div class="row">
   <% @comedians.each do |comedian| %>
    
      <div class="card">
          <a href="/comedian/<%= comedian.id %>"><img class="photo" src=<%= comedian.image %>></a>  
        <div class="card-content" data-comedian-id="<%= comedian.id %>">
          <span class="comedian"><%= comedian.name %> (<%= comedian.country %>)</span> 

          <% if current_user.liked_comedians.member?(comedian) %>
            <span><img class="emoticon" src=<%= image_path('emoji.png') %> alt="laugh"></span>
          <% else %>
          <span><img class="emoticon gray" src=<%= image_path('emoji.png') %> alt="laugh"></span>
        <% end %>
        </div>
      </div> 
      <% end %>
   </div>
</div>

app/views/comedians/new.html.erb
<div class="container">
  <div class="row">
      <div class="col s12 m10 offset-m1">
        <div class="card-panel white">
          <div class="row">
          <h2 class="flow-text heading"><strong>Add a Comedian to the Database - Feature Coming Soon!</strong></h2>
          <%= form_for(:comedian, url: comedian_new_path) do |f|  %>
            <div class="input-field col s12">
             <%= f.text_field :name, class: 'validate', required: true, disabled: true %>
             <%= f.label :name, "Comedian's Name" %>
            </div>
            <div class="input-field col s12">
              <%= f.text_field :country, class: 'validate', required: true, disabled: true %>
              <%= f.label :country, "Country" %>
            </div>
            <div class="input-field col s12">
                <%= f.text_field :image_url, class: 'validate', required: true, disabled: true %>
                <%= f.label :image_url, "Image URL" %>
            </div>
                <%= f.submit "Submit" , class: "btn disabled" %></%>
              <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/comedians/show.html.erb
<div class="container">

  <div class="row">
      <div class="card">
        <div class="card-image">
          <img src=<%= @comedian.image %>>
        </div>
        <div class="card-content" data-comedian-id="<%= @comedian.id %>">
          <span class="comedian"><%= @comedian.name %> (<%= @comedian.country %>)</span> 
          <% if current_user.liked_comedians.member?(@comedian) %>
            <span><img class="emoticon" src=<%= image_path('emoji.png') %> alt="laugh"></span>
          <% else %>
          <span><img class="emoticon gray" src=<%= image_path('emoji.png') %> alt="laugh"></span>
        <% end %>
        </div>
      </div>
  </div>

  <h3 class="flow-text heading">If <%= @comedian.name %> makes you laugh, you might also like:</h3>

  
  <div class="row">
   <% @comedian.similar_comedians[0..3].each do |comedian| %>

      <div class="card">
          <a href="../comedian/<%= comedian.id  %>"><img class="photo" src=<%= comedian.image %>></a>  
        <div class="card-content" data-comedian-id="<%= comedian.id %>">
          <span class="comedian"><%= comedian.name %> (<%= comedian.country %>)</span> 

          <% if current_user.liked_comedians.member?(comedian) %>
            <span><img class="emoticon" src=<%= image_path('emoji.png') %> alt="laugh"></span>
          <% else %>
          <span><img class="emoticon gray" src=<%= image_path('emoji.png') %> alt="laugh"></span>
        <% end %>
        </div>
      </div> 
    <% end %>
  </div>




</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Make me Laugh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>
  <!-- Favicon -->
  <link rel="icon" type="image/png" href="/favicon.ico">
</head>
<body>



<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Make me Laugh</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><form action="/search" method="get">
        <div class="input-field">
          <input id="search" type="search" name="search" required>
          <label for="search"><i class="material-icons">search</i></label>
          <i class="material-icons">close</i>
        </div>
      </form></li>
      <li><a class="modal-trigger" href="#modal1">About</a></li>
      <li><a href="/user/likes">My Likes</a></li>
      <li><a href="/user/suggestions">Recommendations</a></li>
      <% if logged_in? %>
        <li><a href="/comedian/new">Add a Comedian</a></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      <% else %>
        <li><a href="/login">Login</a></li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><form action="/search" method="get">
        <div class="input-field">
          <input id="search" type="search" name="search" required>
          <label for="search"><i class="material-icons" id="mobile-search">search</i></label>
        </div>
      </form></li>
      <li><a class="modal-trigger" href="#modal1">About</a></li>
      <li><a href="/user/likes">My Likes</a></li>
      <li><a href="/user/suggestions">Recomendations</a></li>
      <% if logged_in? %>
        <li><a href="/comedian/new">Add a Comedian</a></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      <% else %>
        <li><a href="/login">Login</a></li>
      <% end %>
    </ul>
  </div>
</nav>

<!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h5>Ever wondered how to find new comedians you might enjoy?</h5>
      <p>Select your favourite comedians by clicking on the laughter emoticons.</p>
      <p>Personal recommendations are accessible once you have selected at least one.</p>
      <p>Alternatively, click on a comedian to see recommendations for similar comedians.</p>
      <a href="#!" class="modal-action modal-close btn-flat">Close</a>
    </div>
  </div>


<%= yield %>

</body>
</html>

<script>
$(document).ready(function() {
  $('.emoticon').on('click', toggleLike);
  $('.button-collapse').sideNav();
  $('.modal-trigger').leanModal({
    dismissible: true,
    in_duration: 300, 
    out_duration: 200
  });
});
</script>

app/views/users/likes.html.erb
<div class="container">
  <% unless current_user.has_likes? %>
    <h3 class="flow-text heading">Select at least one comedian who makes you laugh to see your likes here!</h3>
    <a href="/" class="btn waves-effect waves-light">BACK</a>
  <% end %>

  <div class="row">
   <% @comedians.each do |comedian| %>

      <div class="card">
          <a href="../comedian/<%= comedian.id  %>"><img class="photo" src=<%= comedian.image %>></a>  
        <div class="card-content" data-comedian-id="<%= comedian.id %>">
          <span class="comedian"><%= comedian.name %> (<%= comedian.country %>)</span> 

          <% if current_user.liked_comedians.member?(comedian) %>
            <span><img class="emoticon" src=<%= image_path('emoji.png') %> alt="laugh"></span>
          <% else %>
          <span><img class="emoticon gray" src=<%= image_path('emoji.png') %> alt="laugh"></span>
        <% end %>
        </div>
      </div> 
    <% end %>
  </div>

</div>

app/views/users/new.html.erb
<% if alert %>
  <script>
      Materialize.toast("Passwords don't match, please try again", 3000, 'rounded');
  </script>
<% end %>

<div class="container">
  <div class="row">
      <div class="col s12 m10 offset-m1">
        <div class="card-panel white">
          <div class="row">
          <h2 class="flow-text heading"><strong>Create an account to add to the comedy database</strong></h2> 
          <%= form_for(:user, url: signup_path) do |f|  %>
            <div class="input-field col s12">
             <%= f.text_field :name, class: 'validate', required: true %>
             <%= f.label :name, "Name" %>
            </div>
            <div class="input-field col s12">
              <%= f.text_field :email, class: 'validate', type: 'email', required: true %>
              <%= f.label :email, "Email", :'data-error' => "Please enter a valid email address" %>
            </div>
            <div class="input-field col s12">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'validate', type: 'password', required: true %>
            </div>
            <div class="input-field col s12">
                <%= f.label :password_confirmation, "Confirm Password" %>
                <%= f.password_field :password_confirmation, class: "validate",  type: 'password', required: true %>
            </div>
                <%= f.submit "Sign up" , class: "btn waves-effect waves-light" %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/suggestions.html.erb
<div class="container">
  <div class="row">
    <% if current_user.has_likes? %>
      <h3 class="flow-text heading">Based on a highly scientific matching process of your favourite comedians and those of other users, these comedians have a high probabilty of also making you laugh</h3>
      
      <% @comedians[0..3].each do |comedian| %>
      <div class="card">
        <a href="../comedian/<%= comedian.id %>"><img class="photo" src=<%= comedian.image %>></a>  
          <div class="card-content" data-comedian-id="<%= comedian.id %>">
            <span class="comedian"><%= comedian.name %> (<%= comedian.country %>)</span> 

            <% if current_user.liked_comedians.member?(comedian) %>
              <span><img class="emoticon" src=<%= image_path('emoji.png') %> alt="laugh"></span>
            <% else %>
            <span><img class="emoticon gray" src=<%= image_path('emoji.png') %> alt="laugh"></span>
          <% end %>
          </div>
        </div> 
      <% end %>
  </div>
    <% else %>
      <h3 class="flow-text heading">Select at least one comedian who makes you laugh to see recommendations here!</h3>
      <a href="/" class="btn waves-effect waves-light">BACK</a>
    <% end %>  
</div>